# Generated by Django 4.0.3 on 2022-03-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=150)),
                ('date_birthday', models.DateField()),
                ('email', models.EmailField(max_length=255)),
                ('number_mobile', models.CharField(max_length=150)),
                ('count_event', models.IntegerField()),
                ('group', models.CharField(max_length=15)),
            ],
        ),
    ]
