# Generated by Django 4.0.3 on 2022-03-29 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_event', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ListLevelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_level_event', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.listlevelevent')),
                ('title_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.listevent')),
            ],
        ),
    ]
