# Generated by Django 4.0.3 on 2022-03-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_listevent_listlevelevent_userevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listlevelevent',
            old_name='list_level_event',
            new_name='level_event',
        ),
    ]
