# Generated by Django 4.0.3 on 2022-03-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_rename_list_level_event_listlevelevent_level_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_place', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userevent',
            name='place',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cabinet.placeevent'),
            preserve_default=False,
        ),
    ]
