# Generated by Django 4.0.3 on 2022-03-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_remove_placeevent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='member_event',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='cabinet.datauser'),
            preserve_default=False,
        ),
    ]
