# Generated by Django 4.0.3 on 2022-03-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_datauser_image_userevent_document_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEvent',
            new_name='Event',
        ),
    ]
