# Generated by Django 4.0.3 on 2022-03-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_rename_userevent_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_group', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='datauser',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.group'),
        ),
    ]
