# Generated by Django 4.0.3 on 2022-03-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_group_alter_datauser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, to='cabinet.group'),
            preserve_default=False,
        ),
    ]
